# Generated by Django 5.1.1 on 2024-10-08 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthfacilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
