# Generated by Django 5.1.1 on 2024-10-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfacilities', '0003_healthfacilities_geom_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='amenity',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='healthcare',
            field=models.CharField(max_length=167, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='operatorty',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
