# Generated by Django 5.1.1 on 2024-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genderclimate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_of_kin',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
